//
//  AlbumObject.swift
//  My Song Comparison
//
//  Created by Jarred Davis on 1/21/23.
//

import Foundation

struct AlbumObject:Decodable {
    var id: String
    var artists:[AlbumArtistObject]
    var images:[ImageObject]
    var name:String
    var releaseDate:String
    
    private enum CodingKeys: String, CodingKey {
        case id, artists, images,
             name
        case releaseDate = "release_date"
    }
}

struct AlbumArtistObject:Decodable  {
    var id:String
    var name:String
}


/*
 {
   "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg/albums?offset=0&limit=20&include_groups=album,single,compilation,appears_on&locale=en-US,en;q=0.9",
   "items": [
     {
       "album_group": "album",
       "album_type": "album",
       "artists": [
         {
           "external_urls": {
             "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
           },
           "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
           "id": "0TnOYISbd1XYRBk9myaseg",
           "name": "Pitbull",
           "type": "artist",
           "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
         }
       ],
       "external_urls": {
         "spotify": "https://open.spotify.com/album/6nCJAxRvXmPkPiZo8Vh5ZG"
       },
       "href": "https://api.spotify.com/v1/albums/6nCJAxRvXmPkPiZo8Vh5ZG",
       "id": "6nCJAxRvXmPkPiZo8Vh5ZG",
       "images": [
         {
           "height": 640,
           "url": "https://i.scdn.co/image/ab67616d0000b273f0dd8e557b66318ea8e6978d",
           "width": 640
         },
         {
           "height": 300,
           "url": "https://i.scdn.co/image/ab67616d00001e02f0dd8e557b66318ea8e6978d",
           "width": 300
         },
         {
           "height": 64,
           "url": "https://i.scdn.co/image/ab67616d00004851f0dd8e557b66318ea8e6978d",
           "width": 64
         }
       ],
       "name": "Libertad 548",
       "release_date": "2019-09-27",
       "release_date_precision": "day",
       "total_tracks": 15,
       "type": "album",
       "uri": "spotify:album:6nCJAxRvXmPkPiZo8Vh5ZG"
     },
     {
       "album_group": "album",
       "album_type": "album",
       "artists": [
         {
           "external_urls": {
             "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
           },
           "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
           "id": "0TnOYISbd1XYRBk9myaseg",
           "name": "Pitbull",
           "type": "artist",
           "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
         },
         {
           "external_urls": {
             "spotify": "https://open.spotify.com/artist/6RFjbxELOWFXv54t6ccuRZ"
           },
           "href": "https://api.spotify.com/v1/artists/6RFjbxELOWFXv54t6ccuRZ",
           "id": "6RFjbxELOWFXv54t6ccuRZ",
           "name": "Jorge Gomez",
           "type": "artist",
           "uri": "spotify:artist:6RFjbxELOWFXv54t6ccuRZ"
         }
       ],
       "available_markets": [
         "AD",
         "AE",
         "AG",
         "AL",
         "AM",
         "AO",
         "AR",
         "AT",
         "AU",
         "AZ",
         "BA",
         "BB",
         "BD",
         "BE",
         "BF",
         "BG",
         "BH",
         "BI",
         "BJ",
         "BN",
         "BO",
         "BR",
         "BS",
         "BT",
         "BW",
         "BY",
         "BZ",
         "CA",
         "CD",
         "CG",
         "CH",
         "CI",
         "CL",
         "CM",
         "CO",
         "CR",
         "CV",
         "CW",
         "CY",
         "CZ",
         "DE",
         "DJ",
         "DK",
         "DM",
         "DO",
         "DZ",
         "EC",
         "EE",
         "EG",
         "ES",
         "ET",
         "FI",
         "FJ",
         "FM",
         "FR",
         "GA",
         "GB",
         "GD",
         "GE",
         "GH",
         "GM",
         "GN",
         "GQ",
         "GR",
         "GT",
         "GW",
         "GY",
         "HK",
         "HN",
         "HR",
         "HT",
         "HU",
         "ID",
         "IE",
         "IL",
         "IN",
         "IQ",
         "IS",
         "IT",
         "JM",
         "JO",
         "JP",
         "KE",
         "KG",
         "KH",
         "KI",
         "KM",
         "KN",
         "KR",
         "KW",
         "KZ",
         "LA",
         "LB",
         "LC",
         "LI",
         "LK",
         "LR",
         "LS",
         "LT",
         "LU",
         "LV",
         "LY",
         "MA",
         "MC",
         "MD",
         "ME",
         "MG",
         "MH",
         "MK",
         "ML",
         "MN",
         "MO",
         "MR",
         "MT",
         "MU",
         "MV",
         "MW",
         "MX",
         "MY",
         "MZ",
         "NA",
         "NE",
         "NG",
         "NI",
         "NL",
         "NO",
         "NP",
         "NR",
         "NZ",
         "OM",
         "PA",
         "PE",
         "PG",
         "PH",
         "PK",
         "PL",
         "PS",
         "PT",
         "PW",
         "PY",
         "QA",
         "RO",
         "RS",
         "RW",
         "SA",
         "SB",
         "SC",
         "SE",
         "SG",
         "SI",
         "SK",
         "SL",
         "SM",
         "SN",
         "SR",
         "ST",
         "SV",
         "SZ",
         "TD",
         "TG",
         "TH",
         "TJ",
         "TL",
         "TN",
         "TO",
         "TR",
         "TT",
         "TV",
         "TW",
         "TZ",
         "UA",
         "UG",
         "US",
         "UY",
         "UZ",
         "VC",
         "VE",
         "VN",
         "VU",
         "WS",
         "XK",
         "ZA",
         "ZM",
         "ZW"
       ],
       "external_urls": {
         "spotify": "https://open.spotify.com/album/6ZSNnOY2ESMNoVQ5DdvHrj"
       },
       "href": "https://api.spotify.com/v1/albums/6ZSNnOY2ESMNoVQ5DdvHrj",
       "id": "6ZSNnOY2ESMNoVQ5DdvHrj",
       "images": [
         {
           "height": 640,
           "url": "https://i.scdn.co/image/ab67616d0000b273bfb673e097b39939d6f91874",
           "width": 640
         },
         {
           "height": 300,
           "url": "https://i.scdn.co/image/ab67616d00001e02bfb673e097b39939d6f91874",
           "width": 300
         },
         {
           "height": 64,
           "url": "https://i.scdn.co/image/ab67616d00004851bfb673e097b39939d6f91874",
           "width": 64
         }
       ],
       "name": "Gotti (Original Motion Picture Soundtrack)",
       "release_date": "2018-06-14",
       "release_date_precision": "day",
       "total_tracks": 19,
       "type": "album",
       "uri": "spotify:album:6ZSNnOY2ESMNoVQ5DdvHrj"
     },
     {
       "album_group": "album",
       "album_type": "album",
       "artists": [
         {
           "external_urls": {
             "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
           },
           "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
           "id": "0TnOYISbd1XYRBk9myaseg",
           "name": "Pitbull",
           "type": "artist",
           "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
         }
       ],
       "available_markets": [
         "AD",
         "AE",
         "AG",
         "AL",
         "AM",
         "AO",
         "AR",
         "AT",
         "AU",
         "AZ",
         "BA",
         "BB",
         "BD",
         "BE",
         "BF",
         "BG",
         "BH",
         "BI",
         "BJ",
         "BN",
         "BO",
         "BR",
         "BS",
         "BT",
         "BW",
         "BY",
         "BZ",
         "CA",
         "CD",
         "CG",
         "CH",
         "CI",
         "CL",
         "CM",
         "CO",
         "CR",
         "CV",
         "CW",
         "CY",
         "CZ",
         "DE",
         "DJ",
         "DK",
         "DM",
         "DO",
         "DZ",
         "EC",
         "EE",
         "EG",
         "ES",
         "ET",
         "FI",
         "FJ",
         "FM",
         "FR",
         "GA",
         "GB",
         "GD",
         "GE",
         "GH",
         "GM",
         "GN",
         "GQ",
         "GR",
         "GT",
         "GW",
         "GY",
         "HK",
         "HN",
         "HR",
         "HT",
         "HU",
         "ID",
         "IE",
         "IL",
         "IN",
         "IQ",
         "IS",
         "IT",
         "JM",
         "JO",
         "JP",
         "KE",
         "KG",
         "KH",
         "KI",
         "KM",
         "KN",
         "KR",
         "KW",
         "KZ",
         "LA",
         "LB",
         "LC",
         "LI",
         "LK",
         "LR",
         "LS",
         "LT",
         "LU",
         "LV",
         "LY",
         "MA",
         "MC",
         "MD",
         "ME",
         "MG",
         "MH",
         "MK",
         "ML",
         "MN",
         "MO",
         "MR",
         "MT",
         "MU",
         "MV",
         "MW",
         "MX",
         "MY",
         "MZ",
         "NA",
         "NE",
         "NG",
         "NI",
         "NL",
         "NO",
         "NP",
         "NR",
         "NZ",
         "OM",
         "PA",
         "PE",
         "PG",
         "PH",
         "PK",
         "PL",
         "PS",
         "PT",
         "PW",
         "PY",
         "QA",
         "RO",
         "RS",
         "RW",
         "SA",
         "SB",
         "SC",
         "SE",
         "SG",
         "SI",
         "SK",
         "SL",
         "SM",
         "SN",
         "SR",
         "ST",
         "SV",
         "SZ",
         "TD",
         "TG",
         "TH",
         "TJ",
         "TL",
         "TN",
         "TO",
         "TR",
         "TT",
         "TV",
         "TW",
         "TZ",
         "UA",
         "UG",
         "US",
         "UY",
         "UZ",
         "VC",
         "VE",
         "VN",
         "VU",
         "WS",
         "XK",
         "ZA",
         "ZM",
         "ZW"
       ],
       "external_urls": {
         "spotify": "https://open.spotify.com/album/4jtKPpBQ5eneMwEI94f5Y0"
       },
       "href": "https://api.spotify.com/v1/albums/4jtKPpBQ5eneMwEI94f5Y0",
       "id": "4jtKPpBQ5eneMwEI94f5Y0",
       "images": [
         {
           "height": 640,
           "url": "https://i.scdn.co/image/ab67616d0000b273847d47b2d33517f0e8b2b958",
           "width": 640
         },
         {
           "height": 300,
           "url": "https://i.scdn.co/image/ab67616d00001e02847d47b2d33517f0e8b2b958",
           "width": 300
         },
         {
           "height": 64,
           "url": "https://i.scdn.co/image/ab67616d00004851847d47b2d33517f0e8b2b958",
           "width": 64
         }
       ],
       "name": "Climate Change",
       "release_date": "2017-03-17",
       "release_date_precision": "day",
       "total_tracks": 12,
       "type": "album",
       "uri": "spotify:album:4jtKPpBQ5eneMwEI94f5Y0"
     },
     {
       "album_group": "album",
       "album_type": "album",
       "artists": [
         {
           "external_urls": {
             "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
           },
           "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
           "id": "0TnOYISbd1XYRBk9myaseg",
           "name": "Pitbull",
           "type": "artist",
           "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
         }
       ],
       "available_markets": [
         "AE",
         "AG",
         "AR",
         "BB",
         "BD",
         "BH",
         "BN",
         "BO",
         "BS",
         "BT",
         "BZ",
         "CA",
         "CL",
         "CO",
         "CR",
         "CW",
         "DM",
         "DO",
         "EC",
         "EG",
         "FJ",
         "FM",
         "GD",
         "GT",
         "GY",
         "HK",
         "HN",
         "HT",
         "ID",
         "IN",
         "IQ",
         "JM",
         "JO",
         "KH",
         "KN",
         "KR",
         "KW",
         "LA",
         "LB",
         "LC",
         "LK",
         "LY",
         "MO",
         "MV",
         "MX",
         "MY",
         "NI",
         "NP",
         "NZ",
         "OM",
         "PA",
         "PE",
         "PH",
         "PK",
         "PS",
         "PY",
         "QA",
         "SA",
         "SG",
         "SR",
         "SV",
         "TH",
         "TL",
         "TT",
         "TW",
         "US",
         "UY",
         "VC",
         "VE",
         "VN",
         "WS"
       ],
       "external_urls": {
         "spotify": "https://open.spotify.com/album/1VnKQDQzS1nR9ixXUa9hN5"
       },
       "href": "https://api.spotify.com/v1/albums/1VnKQDQzS1nR9ixXUa9hN5",
       "id": "1VnKQDQzS1nR9ixXUa9hN5",
       "images": [
         {
           "height": 640,
           "url": "https://i.scdn.co/image/ab67616d0000b273126eadde9c041f501ea1a73e",
           "width": 640
         },
         {
           "height": 300,
           "url": "https://i.scdn.co/image/ab67616d00001e02126eadde9c041f501ea1a73e",
           "width": 300
         },
         {
           "height": 64,
           "url": "https://i.scdn.co/image/ab67616d00004851126eadde9c041f501ea1a73e",
           "width": 64
         }
       ],
       "name": "Climate Change",
       "release_date": "2017-03-17",
       "release_date_precision": "day",
       "total_tracks": 12,
       "type": "album",
       "uri": "spotify:album:1VnKQDQzS1nR9ixXUa9hN5"
     },
     {
       "album_group": "album",
       "album_type": "album",
       "artists": [
         {
           "external_urls": {
             "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
           },
           "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
           "id": "0TnOYISbd1XYRBk9myaseg",
           "name": "Pitbull",
           "type": "artist",
           "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
         }
       ],
       "available_markets": [
         "AE",
         "AG",
         "AO",
         "AR",
         "AU",
         "AZ",
         "BB",
         "BD",
         "BF",
         "BH",
         "BI",
         "BJ",
         "BN",
         "BO",
         "BR",
         "BS",
         "BT",
         "BW",
         "BZ",
         "CA",
         "CD",
         "CG",
         "CI",
         "CL",
         "CM",
         "CO",
         "CR",
         "CV",
         "DJ",
         "DM",
         "DO",
         "DZ",
         "EC",
         "EG",
         "ET",
         "FJ",
         "FM",
         "GA",
         "GD",
         "GH",
         "GM",
         "GN",
         "GQ",
         "GT",
         "GW",
         "GY",
         "HK",
         "HN",
         "HT",
         "ID",
         "IN",
         "IQ",
         "JM",
         "JO",
         "JP",
         "KE",
         "KH",
         "KI",
         "KM",
         "KN",
         "KR",
         "KW",
         "LA",
         "LB",
         "LC",
         "LK",
         "LR",
         "LS",
         "LY",
         "MA",
         "MG",
         "MH",
         "ML",
         "MN",
         "MO",
         "MR",
         "MU",
         "MV",
         "MW",
         "MX",
         "MY",
         "MZ",
         "NA",
         "NE",
         "NG",
         "NI",
         "NP",
         "NR",
         "NZ",
         "OM",
         "PA",
         "PE",
         "PG",
         "PH",
         "PK",
         "PS",
         "PW",
         "PY",
         "QA",
         "RW",
         "SA",
         "SB",
         "SC",
         "SG",
         "SL",
         "SN",
         "SR",
         "ST",
         "SV",
         "SZ",
         "TD",
         "TG",
         "TH",
         "TL",
         "TN",
         "TO",
         "TT",
         "TV",
         "TW",
         "TZ",
         "UG",
         "US",
         "UY",
         "VC",
         "VE",
         "VN",
         "VU",
         "WS",
         "ZA",
         "ZM",
         "ZW"
       ],
       "external_urls": {
         "spotify": "https://open.spotify.com/album/5PZWGWwRwA0PJCET9BwBAm"
       },
       "href": "https://api.spotify.com/v1/albums/5PZWGWwRwA0PJCET9BwBAm",
       "id": "5PZWGWwRwA0PJCET9BwBAm",
       "images": [
         {
           "height": 640,
           "url": "https://i.scdn.co/image/ab67616d0000b273a1cc249569898d31407fcf7c",
           "width": 640
         },
         {
           "height": 300,
           "url": "https://i.scdn.co/image/ab67616d00001e02a1cc249569898d31407fcf7c",
           "width": 300
         },
         {
           "height": 64,
           "url": "https://i.scdn.co/image/ab67616d00004851a1cc249569898d31407fcf7c",
           "width": 64
         }
       ],
       "name": "Dale",
       "release_date": "2015-07-17",
       "release_date_precision": "day",
       "total_tracks": 12,
       "type": "album",
       "uri": "spotify:album:5PZWGWwRwA0PJCET9BwBAm"
     },
     {
       "album_group": "album",
       "album_type": "album",
       "artists": [
         {
           "external_urls": {
             "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
           },
           "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
           "id": "0TnOYISbd1XYRBk9myaseg",
           "name": "Pitbull",
           "type": "artist",
           "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
         }
       ],
       "available_markets": [
         "AD",
         "AE",
         "AG",
         "AL",
         "AM",
         "AO",
         "AR",
         "AT",
         "AU",
         "AZ",
         "BA",
         "BB",
         "BD",
         "BE",
         "BF",
         "BG",
         "BH",
         "BI",
         "BJ",
         "BN",
         "BO",
         "BR",
         "BS",
         "BT",
         "BW",
         "BY",
         "BZ",
         "CA",
         "CD",
         "CG",
         "CH",
         "CI",
         "CL",
         "CM",
         "CO",
         "CR",
         "CV",
         "CW",
         "CY",
         "CZ",
         "DE",
         "DJ",
         "DK",
         "DM",
         "DO",
         "DZ",
         "EC",
         "EE",
         "EG",
         "ES",
         "ET",
         "FI",
         "FJ",
         "FM",
         "FR",
         "GA",
         "GB",
         "GD",
         "GE",
         "GH",
         "GM",
         "GN",
         "GQ",
         "GR",
         "GT",
         "GW",
         "GY",
         "HK",
         "HN",
         "HR",
         "HT",
         "HU",
         "ID",
         "IE",
         "IL",
         "IN",
         "IQ",
         "IS",
         "IT",
         "JM",
         "JO",
         "JP",
         "KE",
         "KG",
         "KH",
         "KI",
         "KM",
         "KN",
         "KR",
         "KW",
         "KZ",
         "LA",
         "LB",
         "LC",
         "LI",
         "LK",
         "LR",
         "LS",
         "LT",
         "LU",
         "LV",
         "LY",
         "MA",
         "MC",
         "MD",
         "ME",
         "MG",
         "MH",
         "MK",
         "ML",
         "MN",
         "MO",
         "MR",
         "MT",
         "MU",
         "MV",
         "MW",
         "MX",
         "MY",
         "MZ",
         "NA",
         "NE",
         "NG",
         "NI",
         "NL",
         "NO",
         "NP",
         "NR",
         "NZ",
         "OM",
         "PA",
         "PE",
         "PG",
         "PH",
         "PK",
         "PL",
         "PS",
         "PT",
         "PW",
         "PY",
         "QA",
         "RO",
         "RS",
         "RW",
         "SA",
         "SB",
         "SC",
         "SE",
         "SG",
         "SI",
         "SK",
         "SL",
         "SM",
         "SN",
         "SR",
         "ST",
         "SV",
         "SZ",
         "TD",
         "TG",
         "TH",
         "TJ",
         "TL",
         "TN",
         "TO",
         "TR",
         "TT",
         "TV",
         "TW",
         "TZ",
         "UA",
         "UG",
         "US",
         "UY",
         "UZ",
         "VC",
         "VE",
         "VN",
         "VU",
         "WS",
         "XK",
         "ZA",
         "ZM",
         "ZW"
       ],
       "external_urls": {
         "spotify": "https://open.spotify.com/album/4EUf4YyNjuXypWY6W5wEDm"
       },
       "href": "https://api.spotify.com/v1/albums/4EUf4YyNjuXypWY6W5wEDm",
       "id": "4EUf4YyNjuXypWY6W5wEDm",
       "images": [
         {
           "height": 640,
           "url": "https://i.scdn.co/image/ab67616d0000b2731e340d1480e7bb29a45e3bd7",
           "width": 640
         },
         {
           "height": 300,
           "url": "https://i.scdn.co/image/ab67616d00001e021e340d1480e7bb29a45e3bd7",
           "width": 300
         },
         {
           "height": 64,
           "url": "https://i.scdn.co/image/ab67616d000048511e340d1480e7bb29a45e3bd7",
           "width": 64
         }
       ],
       "name": "Globalization",
       "release_date": "2014-11-21",
       "release_date_precision": "day",
       "total_tracks": 11,
       "type": "album",
       "uri": "spotify:album:4EUf4YyNjuXypWY6W5wEDm"
     },
     {
       "album_group": "album",
       "album_type": "album",
       "artists": [
         {
           "external_urls": {
             "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
           },
           "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
           "id": "0TnOYISbd1XYRBk9myaseg",
           "name": "Pitbull",
           "type": "artist",
           "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
         }
       ],
       "available_markets": [
         "AE",
         "AG",
         "AO",
         "AR",
         "AU",
         "BB",
         "BD",
         "BF",
         "BH",
         "BI",
         "BJ",
         "BN",
         "BO",
         "BS",
         "BT",
         "BW",
         "BZ",
         "CA",
         "CD",
         "CG",
         "CI",
         "CL",
         "CM",
         "CO",
         "CR",
         "CV",
         "CW",
         "DJ",
         "DM",
         "DO",
         "EC",
         "EG",
         "ET",
         "FJ",
         "FM",
         "GA",
         "GD",
         "GH",
         "GM",
         "GN",
         "GQ",
         "GT",
         "GW",
         "GY",
         "HK",
         "HN",
         "HT",
         "ID",
         "IE",
         "IN",
         "IQ",
         "JM",
         "JO",
         "JP",
         "KE",
         "KH",
         "KI",
         "KM",
         "KN",
         "KR",
         "KW",
         "LA",
         "LB",
         "LC",
         "LK",
         "LR",
         "LS",
         "LY",
         "MG",
         "MH",
         "ML",
         "MO",
         "MR",
         "MU",
         "MV",
         "MW",
         "MX",
         "MY",
         "MZ",
         "NA",
         "NE",
         "NG",
         "NI",
         "NP",
         "NR",
         "NZ",
         "OM",
         "PA",
         "PE",
         "PG",
         "PH",
         "PK",
         "PS",
         "PW",
         "PY",
         "QA",
         "RW",
         "SA",
         "SB",
         "SC",
         "SG",
         "SL",
         "SN",
         "SR",
         "ST",
         "SV",
         "SZ",
         "TD",
         "TG",
         "TH",
         "TL",
         "TO",
         "TT",
         "TV",
         "TW",
         "TZ",
         "UG",
         "US",
         "UY",
         "VC",
         "VE",
         "VN",
         "VU",
         "WS",
         "ZA",
         "ZM",
         "ZW"
       ],
       "external_urls": {
         "spotify": "https://open.spotify.com/album/398EKzFttiMH4ojxOsnd7t"
       },
       "href": "https://api.spotify.com/v1/albums/398EKzFttiMH4ojxOsnd7t",
       "id": "398EKzFttiMH4ojxOsnd7t",
       "images": [
         {
           "height": 640,
           "url": "https://i.scdn.co/image/ab67616d0000b273a586c00a9a8358bb3d091f6b",
           "width": 640
         },
         {
           "height": 300,
           "url": "https://i.scdn.co/image/ab67616d00001e02a586c00a9a8358bb3d091f6b",
           "width": 300
         },
         {
           "height": 64,
           "url": "https://i.scdn.co/image/ab67616d00004851a586c00a9a8358bb3d091f6b",
           "width": 64
         }
       ],
       "name": "Globalization",
       "release_date": "2014-11-21",
       "release_date_precision": "day",
       "total_tracks": 11,
       "type": "album",
       "uri": "spotify:album:398EKzFttiMH4ojxOsnd7t"
     },
     {
       "album_group": "album",
       "album_type": "album",
       "artists": [
         {
           "external_urls": {
             "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
           },
           "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
           "id": "0TnOYISbd1XYRBk9myaseg",
           "name": "Pitbull",
           "type": "artist",
           "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
         }
       ],
       "available_markets": [
         "US"
       ],
       "external_urls": {
         "spotify": "https://open.spotify.com/album/2USiuZqEAyfOcKmcujg4hs"
       },
       "href": "https://api.spotify.com/v1/albums/2USiuZqEAyfOcKmcujg4hs",
       "id": "2USiuZqEAyfOcKmcujg4hs",
       "images": [
         {
           "height": 640,
           "url": "https://i.scdn.co/image/ab67616d0000b2736fcb24347773605819a6fd87",
           "width": 640
         },
         {
           "height": 300,
           "url": "https://i.scdn.co/image/ab67616d00001e026fcb24347773605819a6fd87",
           "width": 300
         },
         {
           "height": 64,
           "url": "https://i.scdn.co/image/ab67616d000048516fcb24347773605819a6fd87",
           "width": 64
         }
       ],
       "name": "Global Warming (Deluxe Version)",
       "release_date": "2012-11-19",
       "release_date_precision": "day",
       "total_tracks": 16,
       "type": "album",
       "uri": "spotify:album:2USiuZqEAyfOcKmcujg4hs"
     },
     {
       "album_group": "album",
       "album_type": "album",
       "artists": [
         {
           "external_urls": {
             "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
           },
           "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
           "id": "0TnOYISbd1XYRBk9myaseg",
           "name": "Pitbull",
           "type": "artist",
           "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
         }
       ],
       "available_markets": [
         "US"
       ],
       "external_urls": {
         "spotify": "https://open.spotify.com/album/7I4Vx91kradxSJNwg1ycbq"
       },
       "href": "https://api.spotify.com/v1/albums/7I4Vx91kradxSJNwg1ycbq",
       "id": "7I4Vx91kradxSJNwg1ycbq",
       "images": [
         {
           "height": 640,
           "url": "https://i.scdn.co/image/ab67616d0000b273f575130838bc98c4f2b17312",
           "width": 640
         },
         {
           "height": 300,
           "url": "https://i.scdn.co/image/ab67616d00001e02f575130838bc98c4f2b17312",
           "width": 300
         },
         {
           "height": 64,
           "url": "https://i.scdn.co/image/ab67616d00004851f575130838bc98c4f2b17312",
           "width": 64
         }
       ],
       "name": "Global Warming (Deluxe Version)",
       "release_date": "2012-11-19",
       "release_date_precision": "day",
       "total_tracks": 16,
       "type": "album",
       "uri": "spotify:album:7I4Vx91kradxSJNwg1ycbq"
     },
     {
       "album_group": "album",
       "album_type": "album",
       "artists": [
         {
           "external_urls": {
             "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
           },
           "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
           "id": "0TnOYISbd1XYRBk9myaseg",
           "name": "Pitbull",
           "type": "artist",
           "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
         }
       ],
       "available_markets": [
         "AD",
         "AE",
         "AG",
         "AL",
         "AM",
         "AO",
         "AR",
         "AT",
         "AU",
         "AZ",
         "BA",
         "BB",
         "BD",
         "BE",
         "BF",
         "BG",
         "BH",
         "BI",
         "BJ",
         "BN",
         "BO",
         "BR",
         "BS",
         "BT",
         "BW",
         "BY",
         "BZ",
         "CA",
         "CD",
         "CG",
         "CH",
         "CI",
         "CL",
         "CM",
         "CO",
         "CR",
         "CV",
         "CW",
         "CY",
         "CZ",
         "DE",
         "DJ",
         "DK",
         "DM",
         "DO",
         "DZ",
         "EC",
         "EE",
         "EG",
         "ES",
         "ET",
         "FI",
         "FJ",
         "FM",
         "FR",
         "GA",
         "GB",
         "GD",
         "GE",
         "GH",
         "GM",
         "GN",
         "GQ",
         "GR",
         "GT",
         "GW",
         "GY",
         "HK",
         "HN",
         "HR",
         "HT",
         "HU",
         "ID",
         "IE",
         "IL",
         "IN",
         "IQ",
         "IS",
         "IT",
         "JM",
         "JO",
         "JP",
         "KE",
         "KG",
         "KH",
         "KI",
         "KM",
         "KN",
         "KR",
         "KW",
         "KZ",
         "LA",
         "LB",
         "LC",
         "LI",
         "LK",
         "LR",
         "LS",
         "LT",
         "LU",
         "LV",
         "LY",
         "MA",
         "MC",
         "MD",
         "ME",
         "MG",
         "MH",
         "MK",
         "ML",
         "MN",
         "MO",
         "MR",
         "MT",
         "MU",
         "MV",
         "MW",
         "MX",
         "MY",
         "MZ",
         "NA",
         "NE",
         "NG",
         "NI",
         "NL",
         "NO",
         "NP",
         "NR",
         "NZ",
         "OM",
         "PA",
         "PE",
         "PG",
         "PH",
         "PK",
         "PL",
         "PS",
         "PT",
         "PW",
         "PY",
         "QA",
         "RO",
         "RS",
         "RW",
         "SA",
         "SB",
         "SC",
         "SE",
         "SG",
         "SI",
         "SK",
         "SL",
         "SM",
         "SN",
         "SR",
         "ST",
         "SV",
         "SZ",
         "TD",
         "TG",
         "TH",
         "TJ",
         "TL",
         "TN",
         "TO",
         "TR",
         "TT",
         "TV",
         "TW",
         "TZ",
         "UA",
         "UG",
         "US",
         "UY",
         "UZ",
         "VC",
         "VE",
         "VN",
         "VU",
         "WS",
         "XK",
         "ZA",
         "ZM",
         "ZW"
       ],
       "external_urls": {
         "spotify": "https://open.spotify.com/album/0kv3Rm7PODqJBQaVJiezuB"
       },
       "href": "https://api.spotify.com/v1/albums/0kv3Rm7PODqJBQaVJiezuB",
       "id": "0kv3Rm7PODqJBQaVJiezuB",
       "images": [
         {
           "height": 640,
           "url": "https://i.scdn.co/image/ab67616d0000b2731091bce0b9d981cac5e4091c",
           "width": 640
         },
         {
           "height": 300,
           "url": "https://i.scdn.co/image/ab67616d00001e021091bce0b9d981cac5e4091c",
           "width": 300
         },
         {
           "height": 64,
           "url": "https://i.scdn.co/image/ab67616d000048511091bce0b9d981cac5e4091c",
           "width": 64
         }
       ],
       "name": "I Am Armando - Armando Reloaded",
       "release_date": "2012-07-30",
       "release_date_precision": "day",
       "total_tracks": 14,
       "type": "album",
       "uri": "spotify:album:0kv3Rm7PODqJBQaVJiezuB"
     },
     {
       "album_group": "album",
       "album_type": "album",
       "artists": [
         {
           "external_urls": {
             "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
           },
           "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
           "id": "0TnOYISbd1XYRBk9myaseg",
           "name": "Pitbull",
           "type": "artist",
           "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
         }
       ],
       "available_markets": [
         "AD",
         "AE",
         "AG",
         "AL",
         "AM",
         "AO",
         "AR",
         "AT",
         "AZ",
         "BA",
         "BB",
         "BD",
         "BE",
         "BF",
         "BG",
         "BH",
         "BI",
         "BJ",
         "BN",
         "BO",
         "BR",
         "BS",
         "BT",
         "BW",
         "BY",
         "BZ",
         "CA",
         "CD",
         "CG",
         "CH",
         "CI",
         "CL",
         "CM",
         "CO",
         "CR",
         "CV",
         "CW",
         "CY",
         "CZ",
         "DE",
         "DJ",
         "DK",
         "DM",
         "DO",
         "DZ",
         "EC",
         "EE",
         "EG",
         "ES",
         "ET",
         "FI",
         "FM",
         "FR",
         "GA",
         "GD",
         "GE",
         "GH",
         "GM",
         "GN",
         "GQ",
         "GR",
         "GT",
         "GW",
         "GY",
         "HK",
         "HN",
         "HR",
         "HT",
         "HU",
         "ID",
         "IE",
         "IL",
         "IN",
         "IQ",
         "IS",
         "IT",
         "JM",
         "JO",
         "JP",
         "KE",
         "KG",
         "KH",
         "KM",
         "KN",
         "KR",
         "KW",
         "KZ",
         "LA",
         "LB",
         "LC",
         "LI",
         "LK",
         "LR",
         "LS",
         "LT",
         "LU",
         "LV",
         "LY",
         "MA",
         "MC",
         "MD",
         "ME",
         "MG",
         "MK",
         "ML",
         "MN",
         "MO",
         "MR",
         "MT",
         "MU",
         "MV",
         "MW",
         "MX",
         "MY",
         "MZ",
         "NA",
         "NE",
         "NG",
         "NI",
         "NL",
         "NO",
         "NP",
         "OM",
         "PA",
         "PE",
         "PH",
         "PK",
         "PL",
         "PS",
         "PT",
         "PY",
         "QA",
         "RO",
         "RS",
         "RW",
         "SA",
         "SC",
         "SE",
         "SG",
         "SI",
         "SK",
         "SL",
         "SM",
         "SN",
         "SR",
         "ST",
         "SV",
         "SZ",
         "TD",
         "TG",
         "TH",
         "TJ",
         "TL",
         "TN",
         "TR",
         "TT",
         "TW",
         "TZ",
         "UA",
         "UG",
         "US",
         "UY",
         "UZ",
         "VC",
         "VE",
         "VN",
         "XK",
         "ZA",
         "ZM",
         "ZW"
       ],
       "external_urls": {
         "spotify": "https://open.spotify.com/album/2F7tejLHzTqFq2XLol9ZGy"
       },
       "href": "https://api.spotify.com/v1/albums/2F7tejLHzTqFq2XLol9ZGy",
       "id": "2F7tejLHzTqFq2XLol9ZGy",
       "images": [
         {
           "height": 640,
           "url": "https://i.scdn.co/image/ab67616d0000b273f2486b438645e97b523e4f90",
           "width": 640
         },
         {
           "height": 300,
           "url": "https://i.scdn.co/image/ab67616d00001e02f2486b438645e97b523e4f90",
           "width": 300
         },
         {
           "height": 64,
           "url": "https://i.scdn.co/image/ab67616d00004851f2486b438645e97b523e4f90",
           "width": 64
         }
       ],
       "name": "Global Warming: Meltdown (Deluxe Version)",
       "release_date": "2012",
       "release_date_precision": "year",
       "total_tracks": 17,
       "type": "album",
       "uri": "spotify:album:2F7tejLHzTqFq2XLol9ZGy"
     },
     {
       "album_group": "album",
       "album_type": "album",
       "artists": [
         {
           "external_urls": {
             "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
           },
           "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
           "id": "0TnOYISbd1XYRBk9myaseg",
           "name": "Pitbull",
           "type": "artist",
           "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
         }
       ],
       "available_markets": [
         "AE",
         "AG",
         "AM",
         "AO",
         "AR",
         "AZ",
         "BB",
         "BD",
         "BF",
         "BH",
         "BI",
         "BJ",
         "BN",
         "BO",
         "BS",
         "BW",
         "BY",
         "BZ",
         "CA",
         "CD",
         "CG",
         "CI",
         "CL",
         "CM",
         "CO",
         "CR",
         "CV",
         "CW",
         "DJ",
         "DM",
         "DO",
         "EC",
         "EG",
         "ET",
         "FM",
         "GA",
         "GB",
         "GD",
         "GE",
         "GH",
         "GM",
         "GN",
         "GQ",
         "GT",
         "GW",
         "GY",
         "HK",
         "HN",
         "HT",
         "ID",
         "IE",
         "IN",
         "IQ",
         "JM",
         "JO",
         "JP",
         "KE",
         "KG",
         "KH",
         "KM",
         "KN",
         "KR",
         "KW",
         "KZ",
         "LA",
         "LB",
         "LC",
         "LK",
         "LR",
         "LS",
         "MD",
         "MG",
         "ML",
         "MN",
         "MO",
         "MR",
         "MU",
         "MV",
         "MW",
         "MX",
         "MY",
         "MZ",
         "NA",
         "NE",
         "NG",
         "NI",
         "NP",
         "OM",
         "PA",
         "PE",
         "PH",
         "PK",
         "PS",
         "PY",
         "QA",
         "RW",
         "SA",
         "SC",
         "SG",
         "SL",
         "SN",
         "SR",
         "ST",
         "SV",
         "SZ",
         "TD",
         "TG",
         "TH",
         "TJ",
         "TL",
         "TT",
         "TW",
         "TZ",
         "UA",
         "UG",
         "US",
         "UY",
         "UZ",
         "VC",
         "VE",
         "VN",
         "ZA",
         "ZM",
         "ZW"
       ],
       "external_urls": {
         "spotify": "https://open.spotify.com/album/7sIlk4PsSWt7WhUs0JsFoG"
       },
       "href": "https://api.spotify.com/v1/albums/7sIlk4PsSWt7WhUs0JsFoG",
       "id": "7sIlk4PsSWt7WhUs0JsFoG",
       "images": [
         {
           "height": 640,
           "url": "https://i.scdn.co/image/ab67616d0000b2735c3714e2591b30f2f5194704",
           "width": 640
         },
         {
           "height": 300,
           "url": "https://i.scdn.co/image/ab67616d00001e025c3714e2591b30f2f5194704",
           "width": 300
         },
         {
           "height": 64,
           "url": "https://i.scdn.co/image/ab67616d000048515c3714e2591b30f2f5194704",
           "width": 64
         }
       ],
       "name": "Global Warming: Meltdown (Deluxe Version)",
       "release_date": "2012",
       "release_date_precision": "year",
       "total_tracks": 17,
       "type": "album",
       "uri": "spotify:album:7sIlk4PsSWt7WhUs0JsFoG"
     },
     {
       "album_group": "album",
       "album_type": "album",
       "artists": [
         {
           "external_urls": {
             "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
           },
           "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
           "id": "0TnOYISbd1XYRBk9myaseg",
           "name": "Pitbull",
           "type": "artist",
           "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
         }
       ],
       "available_markets": [
         "AE",
         "AG",
         "AR",
         "AU",
         "BB",
         "BD",
         "BH",
         "BN",
         "BO",
         "BS",
         "BT",
         "BZ",
         "CA",
         "CL",
         "CO",
         "CR",
         "CW",
         "DM",
         "DO",
         "EC",
         "EG",
         "FJ",
         "FM",
         "GD",
         "GT",
         "GY",
         "HK",
         "HN",
         "HT",
         "ID",
         "IN",
         "IQ",
         "JM",
         "JO",
         "JP",
         "KH",
         "KI",
         "KN",
         "KR",
         "KW",
         "LA",
         "LB",
         "LC",
         "LK",
         "LY",
         "MH",
         "MO",
         "MV",
         "MX",
         "MY",
         "NI",
         "NP",
         "NR",
         "NZ",
         "OM",
         "PA",
         "PE",
         "PG",
         "PH",
         "PK",
         "PS",
         "PW",
         "PY",
         "QA",
         "SA",
         "SB",
         "SG",
         "SR",
         "SV",
         "TH",
         "TL",
         "TO",
         "TT",
         "TV",
         "TW",
         "US",
         "UY",
         "VC",
         "VE",
         "VN",
         "VU",
         "WS"
       ],
       "external_urls": {
         "spotify": "https://open.spotify.com/album/3K3wPSsFq3jt0tgZXerYma"
       },
       "href": "https://api.spotify.com/v1/albums/3K3wPSsFq3jt0tgZXerYma",
       "id": "3K3wPSsFq3jt0tgZXerYma",
       "images": [
         {
           "height": 640,
           "url": "https://i.scdn.co/image/ab67616d0000b27314eb5ef4d6fb24b37b6531a6",
           "width": 640
         },
         {
           "height": 300,
           "url": "https://i.scdn.co/image/ab67616d00001e0214eb5ef4d6fb24b37b6531a6",
           "width": 300
         },
         {
           "height": 64,
           "url": "https://i.scdn.co/image/ab67616d0000485114eb5ef4d6fb24b37b6531a6",
           "width": 64
         }
       ],
       "name": "Planet Pit",
       "release_date": "2011-06-17",
       "release_date_precision": "day",
       "total_tracks": 12,
       "type": "album",
       "uri": "spotify:album:3K3wPSsFq3jt0tgZXerYma"
     },
     {
       "album_group": "album",
       "album_type": "album",
       "artists": [
         {
           "external_urls": {
             "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
           },
           "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
           "id": "0TnOYISbd1XYRBk9myaseg",
           "name": "Pitbull",
           "type": "artist",
           "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
         }
       ],
       "available_markets": [
         "AE",
         "AG",
         "AR",
         "BB",
         "BD",
         "BH",
         "BN",
         "BO",
         "BS",
         "BT",
         "BZ",
         "CA",
         "CL",
         "CO",
         "CR",
         "CW",
         "DM",
         "DO",
         "EC",
         "EG",
         "FM",
         "GD",
         "GT",
         "GY",
         "HK",
         "HN",
         "HT",
         "ID",
         "IN",
         "IQ",
         "JM",
         "JO",
         "JP",
         "KH",
         "KN",
         "KR",
         "KW",
         "LA",
         "LB",
         "LC",
         "LK",
         "LY",
         "MO",
         "MV",
         "MX",
         "MY",
         "NI",
         "NP",
         "OM",
         "PA",
         "PE",
         "PH",
         "PK",
         "PS",
         "PY",
         "QA",
         "SA",
         "SG",
         "SR",
         "SV",
         "TH",
         "TL",
         "TT",
         "TW",
         "US",
         "UY",
         "VC",
         "VE",
         "VN"
       ],
       "external_urls": {
         "spotify": "https://open.spotify.com/album/30JZqToNZZH4mN7I0ymGvH"
       },
       "href": "https://api.spotify.com/v1/albums/30JZqToNZZH4mN7I0ymGvH",
       "id": "30JZqToNZZH4mN7I0ymGvH",
       "images": [
         {
           "height": 640,
           "url": "https://i.scdn.co/image/ab67616d0000b273dc2577953f23645b14ff298e",
           "width": 640
         },
         {
           "height": 300,
           "url": "https://i.scdn.co/image/ab67616d00001e02dc2577953f23645b14ff298e",
           "width": 300
         },
         {
           "height": 64,
           "url": "https://i.scdn.co/image/ab67616d00004851dc2577953f23645b14ff298e",
           "width": 64
         }
       ],
       "name": "Planet Pit",
       "release_date": "2011-06-17",
       "release_date_precision": "day",
       "total_tracks": 12,
       "type": "album",
       "uri": "spotify:album:30JZqToNZZH4mN7I0ymGvH"
     },
     {
       "album_group": "album",
       "album_type": "album",
       "artists": [
         {
           "external_urls": {
             "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
           },
           "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
           "id": "0TnOYISbd1XYRBk9myaseg",
           "name": "Pitbull",
           "type": "artist",
           "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
         }
       ],
       "available_markets": [
         "AD",
         "AE",
         "AG",
         "AL",
         "AM",
         "AO",
         "AR",
         "AT",
         "AU",
         "AZ",
         "BA",
         "BB",
         "BD",
         "BE",
         "BF",
         "BG",
         "BH",
         "BI",
         "BJ",
         "BN",
         "BO",
         "BR",
         "BS",
         "BT",
         "BW",
         "BY",
         "BZ",
         "CA",
         "CD",
         "CG",
         "CH",
         "CI",
         "CL",
         "CM",
         "CO",
         "CR",
         "CV",
         "CW",
         "CY",
         "CZ",
         "DE",
         "DJ",
         "DK",
         "DM",
         "DO",
         "DZ",
         "EC",
         "EE",
         "EG",
         "ES",
         "ET",
         "FI",
         "FJ",
         "FM",
         "FR",
         "GA",
         "GB",
         "GD",
         "GE",
         "GH",
         "GM",
         "GN",
         "GQ",
         "GR",
         "GT",
         "GW",
         "GY",
         "HK",
         "HN",
         "HR",
         "HT",
         "HU",
         "ID",
         "IE",
         "IL",
         "IN",
         "IQ",
         "IS",
         "IT",
         "JM",
         "JO",
         "KE",
         "KG",
         "KH",
         "KI",
         "KM",
         "KN",
         "KR",
         "KW",
         "KZ",
         "LA",
         "LB",
         "LC",
         "LI",
         "LK",
         "LR",
         "LS",
         "LT",
         "LU",
         "LV",
         "LY",
         "MA",
         "MC",
         "MD",
         "ME",
         "MG",
         "MH",
         "MK",
         "ML",
         "MN",
         "MO",
         "MR",
         "MT",
         "MU",
         "MV",
         "MW",
         "MX",
         "MY",
         "MZ",
         "NA",
         "NE",
         "NG",
         "NI",
         "NL",
         "NO",
         "NP",
         "NR",
         "NZ",
         "OM",
         "PA",
         "PE",
         "PG",
         "PH",
         "PK",
         "PL",
         "PS",
         "PT",
         "PW",
         "PY",
         "QA",
         "RO",
         "RS",
         "RW",
         "SA",
         "SB",
         "SC",
         "SE",
         "SG",
         "SI",
         "SK",
         "SL",
         "SM",
         "SN",
         "SR",
         "ST",
         "SV",
         "SZ",
         "TD",
         "TG",
         "TH",
         "TJ",
         "TL",
         "TN",
         "TO",
         "TR",
         "TT",
         "TV",
         "TW",
         "TZ",
         "UA",
         "UG",
         "US",
         "UY",
         "UZ",
         "VC",
         "VE",
         "VN",
         "VU",
         "WS",
         "XK",
         "ZA",
         "ZM",
         "ZW"
       ],
       "external_urls": {
         "spotify": "https://open.spotify.com/album/4rG0MhkU6UojACJxkMHIXB"
       },
       "href": "https://api.spotify.com/v1/albums/4rG0MhkU6UojACJxkMHIXB",
       "id": "4rG0MhkU6UojACJxkMHIXB",
       "images": [
         {
           "height": 640,
           "url": "https://i.scdn.co/image/ab67616d0000b2731dc7483a9fcfce54822a2f19",
           "width": 640
         },
         {
           "height": 300,
           "url": "https://i.scdn.co/image/ab67616d00001e021dc7483a9fcfce54822a2f19",
           "width": 300
         },
         {
           "height": 64,
           "url": "https://i.scdn.co/image/ab67616d000048511dc7483a9fcfce54822a2f19",
           "width": 64
         }
       ],
       "name": "Planet Pit (Deluxe Version)",
       "release_date": "2011-06-17",
       "release_date_precision": "day",
       "total_tracks": 16,
       "type": "album",
       "uri": "spotify:album:4rG0MhkU6UojACJxkMHIXB"
     },
     {
       "album_group": "album",
       "album_type": "album",
       "artists": [
         {
           "external_urls": {
             "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
           },
           "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
           "id": "0TnOYISbd1XYRBk9myaseg",
           "name": "Pitbull",
           "type": "artist",
           "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
         }
       ],
       "available_markets": [
         "AE",
         "AG",
         "AR",
         "AU",
         "BB",
         "BD",
         "BH",
         "BN",
         "BO",
         "BR",
         "BS",
         "BT",
         "BZ",
         "CA",
         "CL",
         "CO",
         "CR",
         "CW",
         "DM",
         "DO",
         "EC",
         "EG",
         "FJ",
         "FM",
         "GD",
         "GT",
         "GY",
         "HK",
         "HN",
         "HT",
         "ID",
         "IN",
         "IQ",
         "JM",
         "JO",
         "JP",
         "KH",
         "KI",
         "KN",
         "KR",
         "KW",
         "LA",
         "LB",
         "LC",
         "LK",
         "LY",
         "MH",
         "MO",
         "MV",
         "MX",
         "MY",
         "NI",
         "NP",
         "NR",
         "NZ",
         "OM",
         "PA",
         "PE",
         "PG",
         "PH",
         "PK",
         "PS",
         "PW",
         "PY",
         "QA",
         "SA",
         "SB",
         "SG",
         "SR",
         "SV",
         "TH",
         "TL",
         "TO",
         "TT",
         "TV",
         "TW",
         "US",
         "UY",
         "VC",
         "VE",
         "VN",
         "VU",
         "WS"
       ],
       "external_urls": {
         "spotify": "https://open.spotify.com/album/6QYAJnxQVosXMMszGfVGvO"
       },
       "href": "https://api.spotify.com/v1/albums/6QYAJnxQVosXMMszGfVGvO",
       "id": "6QYAJnxQVosXMMszGfVGvO",
       "images": [
         {
           "height": 640,
           "url": "https://i.scdn.co/image/ab67616d0000b2734d38cf0ef72e9dd9e0a1e64f",
           "width": 640
         },
         {
           "height": 300,
           "url": "https://i.scdn.co/image/ab67616d00001e024d38cf0ef72e9dd9e0a1e64f",
           "width": 300
         },
         {
           "height": 64,
           "url": "https://i.scdn.co/image/ab67616d000048514d38cf0ef72e9dd9e0a1e64f",
           "width": 64
         }
       ],
       "name": "Planet Pit (Deluxe Version)",
       "release_date": "2011-06-17",
       "release_date_precision": "day",
       "total_tracks": 16,
       "type": "album",
       "uri": "spotify:album:6QYAJnxQVosXMMszGfVGvO"
     },
     {
       "album_group": "album",
       "album_type": "album",
       "artists": [
         {
           "external_urls": {
             "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
           },
           "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
           "id": "0TnOYISbd1XYRBk9myaseg",
           "name": "Pitbull",
           "type": "artist",
           "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
         }
       ],
       "available_markets": [
         "AD",
         "AE",
         "AG",
         "AL",
         "AM",
         "AO",
         "AR",
         "AT",
         "AU",
         "AZ",
         "BA",
         "BB",
         "BD",
         "BE",
         "BF",
         "BG",
         "BH",
         "BI",
         "BJ",
         "BN",
         "BO",
         "BR",
         "BS",
         "BT",
         "BW",
         "BY",
         "BZ",
         "CA",
         "CD",
         "CG",
         "CH",
         "CI",
         "CL",
         "CM",
         "CO",
         "CR",
         "CV",
         "CW",
         "CY",
         "CZ",
         "DE",
         "DJ",
         "DK",
         "DM",
         "DO",
         "DZ",
         "EC",
         "EE",
         "EG",
         "ES",
         "ET",
         "FI",
         "FJ",
         "FM",
         "FR",
         "GA",
         "GB",
         "GD",
         "GE",
         "GH",
         "GM",
         "GN",
         "GQ",
         "GR",
         "GT",
         "GW",
         "GY",
         "HK",
         "HN",
         "HR",
         "HT",
         "HU",
         "ID",
         "IE",
         "IL",
         "IN",
         "IQ",
         "IS",
         "IT",
         "JM",
         "JO",
         "JP",
         "KE",
         "KG",
         "KH",
         "KI",
         "KM",
         "KN",
         "KR",
         "KW",
         "KZ",
         "LA",
         "LB",
         "LC",
         "LI",
         "LK",
         "LR",
         "LS",
         "LT",
         "LU",
         "LV",
         "LY",
         "MA",
         "MC",
         "MD",
         "ME",
         "MG",
         "MH",
         "MK",
         "ML",
         "MN",
         "MO",
         "MR",
         "MT",
         "MU",
         "MV",
         "MW",
         "MX",
         "MY",
         "MZ",
         "NA",
         "NE",
         "NG",
         "NI",
         "NL",
         "NO",
         "NP",
         "NR",
         "NZ",
         "OM",
         "PA",
         "PE",
         "PG",
         "PH",
         "PK",
         "PL",
         "PS",
         "PT",
         "PW",
         "PY",
         "QA",
         "RO",
         "RS",
         "RW",
         "SA",
         "SB",
         "SC",
         "SE",
         "SG",
         "SI",
         "SK",
         "SL",
         "SM",
         "SN",
         "SR",
         "ST",
         "SV",
         "SZ",
         "TD",
         "TG",
         "TH",
         "TJ",
         "TL",
         "TN",
         "TO",
         "TR",
         "TT",
         "TV",
         "TW",
         "TZ",
         "UA",
         "UG",
         "US",
         "UY",
         "UZ",
         "VC",
         "VE",
         "VN",
         "VU",
         "WS",
         "XK",
         "ZA",
         "ZM",
         "ZW"
       ],
       "external_urls": {
         "spotify": "https://open.spotify.com/album/1q23hvi1qvoADt2fh7FO7P"
       },
       "href": "https://api.spotify.com/v1/albums/1q23hvi1qvoADt2fh7FO7P",
       "id": "1q23hvi1qvoADt2fh7FO7P",
       "images": [
         {
           "height": 640,
           "url": "https://i.scdn.co/image/ab67616d0000b2733eb0fc423b496236f33cb033",
           "width": 640
         },
         {
           "height": 300,
           "url": "https://i.scdn.co/image/ab67616d00001e023eb0fc423b496236f33cb033",
           "width": 300
         },
         {
           "height": 64,
           "url": "https://i.scdn.co/image/ab67616d000048513eb0fc423b496236f33cb033",
           "width": 64
         }
       ],
       "name": "Armando (Deluxe Version)",
       "release_date": "2010-11-02",
       "release_date_precision": "day",
       "total_tracks": 14,
       "type": "album",
       "uri": "spotify:album:1q23hvi1qvoADt2fh7FO7P"
     },
     {
       "album_group": "album",
       "album_type": "album",
       "artists": [
         {
           "external_urls": {
             "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
           },
           "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
           "id": "0TnOYISbd1XYRBk9myaseg",
           "name": "Pitbull",
           "type": "artist",
           "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
         }
       ],
       "available_markets": [
         "AD",
         "AE",
         "AG",
         "AL",
         "AM",
         "AO",
         "AR",
         "AT",
         "AU",
         "AZ",
         "BA",
         "BB",
         "BD",
         "BE",
         "BF",
         "BG",
         "BH",
         "BI",
         "BJ",
         "BN",
         "BO",
         "BR",
         "BS",
         "BT",
         "BW",
         "BY",
         "BZ",
         "CA",
         "CD",
         "CG",
         "CH",
         "CI",
         "CL",
         "CM",
         "CO",
         "CR",
         "CV",
         "CW",
         "CY",
         "CZ",
         "DE",
         "DJ",
         "DK",
         "DM",
         "DO",
         "DZ",
         "EC",
         "EE",
         "EG",
         "ES",
         "ET",
         "FI",
         "FJ",
         "FM",
         "FR",
         "GA",
         "GB",
         "GD",
         "GE",
         "GH",
         "GM",
         "GN",
         "GQ",
         "GR",
         "GT",
         "GW",
         "GY",
         "HK",
         "HN",
         "HR",
         "HT",
         "HU",
         "ID",
         "IE",
         "IL",
         "IN",
         "IQ",
         "IS",
         "IT",
         "JM",
         "JO",
         "KE",
         "KG",
         "KH",
         "KI",
         "KM",
         "KN",
         "KR",
         "KW",
         "KZ",
         "LA",
         "LB",
         "LC",
         "LI",
         "LK",
         "LR",
         "LS",
         "LT",
         "LU",
         "LV",
         "LY",
         "MA",
         "MC",
         "MD",
         "ME",
         "MG",
         "MH",
         "MK",
         "ML",
         "MN",
         "MO",
         "MR",
         "MT",
         "MU",
         "MV",
         "MW",
         "MX",
         "MY",
         "MZ",
         "NA",
         "NE",
         "NG",
         "NI",
         "NL",
         "NO",
         "NP",
         "NR",
         "NZ",
         "OM",
         "PA",
         "PE",
         "PG",
         "PH",
         "PK",
         "PL",
         "PS",
         "PT",
         "PW",
         "PY",
         "QA",
         "RO",
         "RS",
         "RW",
         "SA",
         "SB",
         "SC",
         "SE",
         "SG",
         "SI",
         "SK",
         "SL",
         "SM",
         "SN",
         "SR",
         "ST",
         "SV",
         "SZ",
         "TD",
         "TG",
         "TH",
         "TJ",
         "TL",
         "TN",
         "TO",
         "TR",
         "TT",
         "TV",
         "TW",
         "TZ",
         "UA",
         "UG",
         "US",
         "UY",
         "UZ",
         "VC",
         "VE",
         "VN",
         "VU",
         "WS",
         "XK",
         "ZA",
         "ZM",
         "ZW"
       ],
       "external_urls": {
         "spotify": "https://open.spotify.com/album/5PeAAIMt9AD5Ph4Te8SbqS"
       },
       "href": "https://api.spotify.com/v1/albums/5PeAAIMt9AD5Ph4Te8SbqS",
       "id": "5PeAAIMt9AD5Ph4Te8SbqS",
       "images": [
         {
           "height": 640,
           "url": "https://i.scdn.co/image/ab67616d0000b2737902b8c9ab1b105e79f77ef9",
           "width": 640
         },
         {
           "height": 300,
           "url": "https://i.scdn.co/image/ab67616d00001e027902b8c9ab1b105e79f77ef9",
           "width": 300
         },
         {
           "height": 64,
           "url": "https://i.scdn.co/image/ab67616d000048517902b8c9ab1b105e79f77ef9",
           "width": 64
         }
       ],
       "name": "Armando",
       "release_date": "2010-11-02",
       "release_date_precision": "day",
       "total_tracks": 12,
       "type": "album",
       "uri": "spotify:album:5PeAAIMt9AD5Ph4Te8SbqS"
     },
     {
       "album_group": "album",
       "album_type": "album",
       "artists": [
         {
           "external_urls": {
             "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
           },
           "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
           "id": "0TnOYISbd1XYRBk9myaseg",
           "name": "Pitbull",
           "type": "artist",
           "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
         }
       ],
       "available_markets": [
         "AD",
         "AE",
         "AG",
         "AL",
         "AM",
         "AO",
         "AR",
         "AT",
         "AZ",
         "BA",
         "BB",
         "BD",
         "BE",
         "BF",
         "BG",
         "BH",
         "BI",
         "BJ",
         "BN",
         "BO",
         "BR",
         "BS",
         "BT",
         "BW",
         "BY",
         "BZ",
         "CA",
         "CD",
         "CG",
         "CH",
         "CI",
         "CL",
         "CM",
         "CO",
         "CR",
         "CV",
         "CW",
         "CY",
         "CZ",
         "DE",
         "DJ",
         "DK",
         "DM",
         "DO",
         "DZ",
         "EC",
         "EE",
         "EG",
         "ES",
         "ET",
         "FI",
         "FM",
         "FR",
         "GA",
         "GB",
         "GD",
         "GE",
         "GH",
         "GM",
         "GN",
         "GQ",
         "GR",
         "GT",
         "GW",
         "GY",
         "HK",
         "HN",
         "HR",
         "HT",
         "HU",
         "ID",
         "IE",
         "IL",
         "IN",
         "IQ",
         "IS",
         "IT",
         "JM",
         "JO",
         "JP",
         "KE",
         "KG",
         "KH",
         "KM",
         "KN",
         "KR",
         "KW",
         "KZ",
         "LA",
         "LB",
         "LC",
         "LI",
         "LK",
         "LR",
         "LS",
         "LT",
         "LU",
         "LV",
         "LY",
         "MA",
         "MC",
         "MD",
         "ME",
         "MG",
         "MK",
         "ML",
         "MN",
         "MO",
         "MR",
         "MT",
         "MU",
         "MV",
         "MW",
         "MX",
         "MY",
         "MZ",
         "NA",
         "NE",
         "NG",
         "NI",
         "NL",
         "NO",
         "NP",
         "OM",
         "PA",
         "PE",
         "PH",
         "PK",
         "PL",
         "PS",
         "PT",
         "PY",
         "QA",
         "RO",
         "RS",
         "RW",
         "SA",
         "SC",
         "SE",
         "SG",
         "SI",
         "SK",
         "SL",
         "SM",
         "SN",
         "SR",
         "ST",
         "SV",
         "SZ",
         "TD",
         "TG",
         "TH",
         "TJ",
         "TL",
         "TN",
         "TR",
         "TT",
         "TW",
         "TZ",
         "UA",
         "UG",
         "US",
         "UY",
         "UZ",
         "VC",
         "VE",
         "VN",
         "XK",
         "ZA",
         "ZM",
         "ZW"
       ],
       "external_urls": {
         "spotify": "https://open.spotify.com/album/00zN65JStpVnpJn9ckMsQI"
       },
       "href": "https://api.spotify.com/v1/albums/00zN65JStpVnpJn9ckMsQI",
       "id": "00zN65JStpVnpJn9ckMsQI",
       "images": [
         {
           "height": 640,
           "url": "https://i.scdn.co/image/ab67616d0000b273956346ed9c201b6de9d3a1a2",
           "width": 640
         },
         {
           "height": 300,
           "url": "https://i.scdn.co/image/ab67616d00001e02956346ed9c201b6de9d3a1a2",
           "width": 300
         },
         {
           "height": 64,
           "url": "https://i.scdn.co/image/ab67616d00004851956346ed9c201b6de9d3a1a2",
           "width": 64
         }
       ],
       "name": "Pitbull Starring In Rebelution",
       "release_date": "2009-08-31",
       "release_date_precision": "day",
       "total_tracks": 14,
       "type": "album",
       "uri": "spotify:album:00zN65JStpVnpJn9ckMsQI"
     },
     {
       "album_group": "album",
       "album_type": "album",
       "artists": [
         {
           "external_urls": {
             "spotify": "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
           },
           "href": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
           "id": "0TnOYISbd1XYRBk9myaseg",
           "name": "Pitbull",
           "type": "artist",
           "uri": "spotify:artist:0TnOYISbd1XYRBk9myaseg"
         }
       ],
       "available_markets": [
         "AE",
         "AG",
         "AL",
         "AM",
         "AO",
         "AR",
         "AZ",
         "BA",
         "BB",
         "BD",
         "BE",
         "BF",
         "BG",
         "BH",
         "BI",
         "BJ",
         "BN",
         "BO",
         "BR",
         "BS",
         "BT",
         "BW",
         "BY",
         "BZ",
         "CA",
         "CD",
         "CG",
         "CH",
         "CI",
         "CL",
         "CM",
         "CO",
         "CR",
         "CV",
         "CW",
         "CY",
         "CZ",
         "DJ",
         "DK",
         "DM",
         "DO",
         "EC",
         "EE",
         "EG",
         "ES",
         "ET",
         "FI",
         "FM",
         "GA",
         "GD",
         "GE",
         "GH",
         "GM",
         "GN",
         "GQ",
         "GR",
         "GT",
         "GW",
         "GY",
         "HK",
         "HN",
         "HR",
         "HT",
         "HU",
         "ID",
         "IE",
         "IL",
         "IN",
         "IQ",
         "IS",
         "IT",
         "JM",
         "JO",
         "JP",
         "KE",
         "KG",
         "KH",
         "KM",
         "KN",
         "KR",
         "KW",
         "KZ",
         "LA",
         "LB",
         "LC",
         "LI",
         "LK",
         "LR",
         "LS",
         "LT",
         "LU",
         "LV",
         "LY",
         "MD",
         "ME",
         "MG",
         "MK",
         "ML",
         "MN",
         "MO",
         "MR",
         "MT",
         "MU",
         "MV",
         "MW",
         "MX",
         "MY",
         "MZ",
         "NA",
         "NE",
         "NG",
         "NI",
         "NL",
         "NO",
         "NP",
         "OM",
         "PA",
         "PE",
         "PH",
         "PK",
         "PL",
         "PS",
         "PT",
         "PY",
         "QA",
         "RO",
         "RS",
         "RW",
         "SA",
         "SC",
         "SE",
         "SG",
         "SI",
         "SK",
         "SL",
         "SM",
         "SN",
         "SR",
         "ST",
         "SV",
         "SZ",
         "TD",
         "TG",
         "TH",
         "TJ",
         "TL",
         "TR",
         "TT",
         "TW",
         "TZ",
         "UA",
         "UG",
         "US",
         "UY",
         "UZ",
         "VC",
         "VE",
         "VN",
         "XK",
         "ZA",
         "ZM",
         "ZW"
       ],
       "external_urls": {
         "spotify": "https://open.spotify.com/album/4RaAjieYFIZRF8uh6GY43r"
       },
       "href": "https://api.spotify.com/v1/albums/4RaAjieYFIZRF8uh6GY43r",
       "id": "4RaAjieYFIZRF8uh6GY43r",
       "images": [
         {
           "height": 640,
           "url": "https://i.scdn.co/image/ab67616d0000b273a511f69870fa68e7ba78c099",
           "width": 640
         },
         {
           "height": 300,
           "url": "https://i.scdn.co/image/ab67616d00001e02a511f69870fa68e7ba78c099",
           "width": 300
         },
         {
           "height": 64,
           "url": "https://i.scdn.co/image/ab67616d00004851a511f69870fa68e7ba78c099",
           "width": 64
         }
       ],
       "name": "Pitbull Starring In Rebelution",
       "release_date": "2009-08-27",
       "release_date_precision": "day",
       "total_tracks": 14,
       "type": "album",
       "uri": "spotify:album:4RaAjieYFIZRF8uh6GY43r"
     }
   ],
   "limit": 20,
   "next": "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg/albums?offset=20&limit=20&include_groups=album,single,compilation,appears_on&locale=en-US,en;q=0.9",
   "offset": 0,
   "previous": null,
   "total": 888
 }
 
 
 */
